//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmMartDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crop()
        {
            this.FarmCrop = new HashSet<FarmCrop>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CropTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Photopath { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual CropType CropType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmCrop> FarmCrop { get; set; }
    }
}
