//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmMartDAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmerMartEntities : DbContext
    {
        public FarmerMartEntities()
            : base("name=FarmerMartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Crop> Crop { get; set; }
        public virtual DbSet<CropType> CropType { get; set; }
        public virtual DbSet<Farm> Farm { get; set; }
        public virtual DbSet<FarmAddress> FarmAddress { get; set; }
        public virtual DbSet<FarmCrop> FarmCrop { get; set; }
        public virtual DbSet<HarvestPeriod> HarvestPeriod { get; set; }
        public virtual DbSet<LocalGovernment> LocalGovernment { get; set; }
        public virtual DbSet<Measurement> Measurement { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Planting> Planting { get; set; }
        public virtual DbSet<Pricing> Pricing { get; set; }
        public virtual DbSet<State> State { get; set; }
    }
}
