//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmMartDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing
    {
        public int Id { get; set; }
        public Nullable<int> FarmId { get; set; }
        public Nullable<int> FarmCropId { get; set; }
        public Nullable<int> MeasurementId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual FarmCrop FarmCrop { get; set; }
        public virtual Measurement Measurement { get; set; }
    }
}
