//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmMartDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmCrop
    {
        public int Id { get; set; }
        public int FarmId { get; set; }
        public int CropVarietyId { get; set; }
        public string Hectarage { get; set; }
        public string YieldPerHectar { get; set; }
        public string CropVarietyNote { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CropPriceId { get; set; }
        public Nullable<int> PlantingId { get; set; }
    
        public virtual CropPrice CropPrice { get; set; }
        public virtual CropVariety CropVariety { get; set; }
        public virtual Farm Farm { get; set; }
        public virtual Planting Planting { get; set; }
    }
}
