//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmMartDAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmerMartEntities : DbContext
    {
        public FarmerMartEntities()
            : base("name=FarmerMartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LocalGovernment> LocalGovernment { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AnimalGender> AnimalGender { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Crop> Crop { get; set; }
        public virtual DbSet<CropPrice> CropPrice { get; set; }
        public virtual DbSet<CropType> CropType { get; set; }
        public virtual DbSet<CropVariety> CropVariety { get; set; }
        public virtual DbSet<Farm> Farm { get; set; }
        public virtual DbSet<FarmCrop> FarmCrop { get; set; }
        public virtual DbSet<FarmLivestock> FarmLivestock { get; set; }
        public virtual DbSet<HarvestPeriod> HarvestPeriod { get; set; }
        public virtual DbSet<LgisticsOffice> LgisticsOffice { get; set; }
        public virtual DbSet<Livestock> Livestock { get; set; }
        public virtual DbSet<LivestockBreed> LivestockBreed { get; set; }
        public virtual DbSet<LivestockPrice> LivestockPrice { get; set; }
        public virtual DbSet<LivestockType> LivestockType { get; set; }
        public virtual DbSet<Measurement> Measurement { get; set; }
        public virtual DbSet<MessageReply> MessageReply { get; set; }
        public virtual DbSet<Messaging> Messaging { get; set; }
        public virtual DbSet<Planting> Planting { get; set; }
        public virtual DbSet<ResearchInstituteOffice> ResearchInstituteOffice { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
