//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmMartDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmLivestock
    {
        public int Id { get; set; }
        public int FarmId { get; set; }
        public int LivestockBreedId { get; set; }
        public int GenderId { get; set; }
        public string Population { get; set; }
        public string QuantityAvailable { get; set; }
        public string Weight { get; set; }
        public Nullable<System.DateTime> HitMarketDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> LivestockPriceId { get; set; }
    
        public virtual AnimalGender AnimalGender { get; set; }
        public virtual Farm Farm { get; set; }
        public virtual LivestockBreed LivestockBreed { get; set; }
        public virtual LivestockPrice LivestockPrice { get; set; }
    }
}
